# Site settings
title: notez
author: Ankit Goyal
author_avatar: http://0.gravatar.com/avatar/d66cc3dd2d00bed9ae96105661e618fa?s=50
email: me@goyalankit.com
description: Blog about whatever.
baseurl: "" # optional
url: "https://goyalankit.github.io/jekyll-lambda"
twitter_username: _goyalankit
github_username: goyalankit
github_repo: goyalankit/os
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: redcarpet #kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
include:
  - .nojekyll
